use super::*;
use std::path::PathBuf;

use crate::command::State;
use crate::command::binding::Binding;
use crate::command::call::{Context, Invocation, Raw, Scope, Source};
use crate::command::definition::Definition;
use crate::command::registry::{RegisterError, Rejection};
use crate::command::shortcut::Shortcut;
use crate::text::command::{Copy, InsertText, Paste, SelectAll};
use crate::{ui, window};

const TEXT_BOX: ui::Id = ui::Id::new("text_box");

struct CustomFlag;
struct SaveAs;
trait MacroTarget: 'static {}

impl target::Category for dyn MacroTarget {}

crate::command!(MacroGenerated {
    name: "macro_generated",
    display: "Macro Generated",
    args: String,
    output: bool,
    hint: "Generated by command macro",
    repeatable: true,
    target: dyn MacroTarget,
});

impl Command for CustomFlag {
    type Args = bool;
    type Output = ();

    const NAME: &'static str = "custom_flag";
    const DISPLAY: &'static str = "Custom Flag";
}

impl Command for SaveAs {
    type Args = PathBuf;
    type Output = ();

    const NAME: &'static str = "save_as";
    const DISPLAY: &'static str = "Save As";
}

const SELECT_ALL: Key = Key::of::<SelectAll>();
const COPY: Key = Key::of::<Copy>();
const INSERT_TEXT: Key = Key::of::<InsertText>();
const CUSTOM_FLAG: Key = Key::of::<CustomFlag>();

struct FlagTarget {
    value: bool,
}

impl Target<CustomFlag> for FlagTarget {
    fn state(&self, _context: &Context) -> State {
        State::active_if(self.value)
    }

    fn invoke(&mut self, args: bool, _invocation: Invocation<CustomFlag>) -> Response<()> {
        self.value = args;
        Response::none()
    }
}

#[test]
fn unregistered_command_is_disabled() {
    let registry = Registry::new();
    let context = Context::path(window::Id::new(1), ui::Path::from(TEXT_BOX));

    assert_eq!(
        registry.state_key(SELECT_ALL, context),
        State::unavailable()
    );
}

#[test]
fn context_specific_state_wins_over_window_fallback() {
    let mut registry = Registry::new();
    let window = window::Id::new(1);

    registry.define::<SelectAll, TestTarget>(|command| command);
    registry.set_state_key(SELECT_ALL, Context::window(window), State::unavailable());
    registry.set_state_key(
        SELECT_ALL,
        Context::path(window, ui::Path::from(TEXT_BOX)),
        State::active(),
    );

    assert_eq!(
        registry.state_key(SELECT_ALL, Context::path(window, ui::Path::from(TEXT_BOX))),
        State::active()
    );
}

#[test]
fn unavailable_and_running_commands_reject_prepared_calls() {
    let mut registry = Registry::new();
    let context = Context::path(window::Id::new(1), ui::Path::from(TEXT_BOX));

    registry.define::<SelectAll, TestTarget>(|command| command);
    registry.set_state_key(SELECT_ALL, context.clone(), State::unavailable());

    assert_eq!(
        registry.prepare_call(Raw::from_key(
            SELECT_ALL,
            Source::Programmatic,
            context.clone()
        )),
        Err(Rejection::Disabled {
            command: SelectAll::NAME,
            context: context.clone(),
        })
    );

    registry.set_state_key(SELECT_ALL, context.clone(), State::available());
    registry.set_running_key(SELECT_ALL, context.clone(), true);

    assert_eq!(
        registry.prepare_call(Raw::from_key(
            SELECT_ALL,
            Source::Programmatic,
            context.clone()
        )),
        Err(Rejection::Running {
            command: SelectAll::NAME,
            context,
        })
    );
}

#[test]
fn command_state_can_override_presentation() {
    let mut registry = Registry::new();
    let context = Context::window(window::Id::new(1));

    registry.define::<SelectAll, TestTarget>(|command| command.with_hint("Select document text"));
    registry.set_state_key(
        SELECT_ALL,
        context.clone(),
        State::available().with_display("Select Everything"),
    );

    let presentation = registry
        .presentation::<SelectAll>(context)
        .expect("registered command should have presentation");

    assert_eq!(presentation.display(), "Select Everything");
    assert_eq!(presentation.hint(), Some("Select document text"));
    assert!(presentation.state().is_available());
}

#[test]
fn binding_projects_optional_command_state() {
    let binding = Binding::of::<SelectAll>();

    assert_eq!(binding.command(), SELECT_ALL);
    assert_eq!(binding.state(), None);

    let binding = binding.available(false).active(true).running(true);
    let state = binding.state().expect("binding should project state");

    assert!(!state.is_available());
    assert!(state.is_active());
    assert!(state.is_running());
}

#[test]
fn registry_projects_registered_target_state() {
    let mut registry = Registry::new();
    let context = Context::window(window::Id::new(1));
    let target = FlagTarget { value: true };

    registry.define::<CustomFlag, FlagTarget>(|command| command);

    assert_eq!(
        registry.configured_state::<CustomFlag>(context.clone()),
        State::available()
    );
    assert!(registry.project_target_states(&target, context.clone()));
    assert_eq!(
        registry.configured_state::<CustomFlag>(context),
        State::active()
    );
}

#[test]
fn registry_rejects_duplicate_commands_and_shortcuts_atomically() {
    let mut registry = Registry::new();
    let shortcut = Shortcut::ctrl('a');

    registry.define::<SelectAll, TestTarget>(|command| command.shortcut(shortcut));

    assert_eq!(
        registry.try_define::<SelectAll, TestTarget>(|command| command),
        Err(RegisterError::DuplicateCommand {
            command: SelectAll::NAME,
        })
    );
    assert_eq!(
        registry.try_define::<Copy, TestTarget>(|command| command.shortcut(shortcut)),
        Err(RegisterError::DuplicateShortcut {
            shortcut,
            existing: SelectAll::NAME,
            duplicate: Copy::NAME,
        })
    );
    assert!(registry.command_key(COPY).is_none());
    assert_eq!(
        registry
            .shortcut_command(shortcut)
            .map(|route| route.command()),
        Some(SELECT_ALL)
    );
}

#[test]
fn registry_accepts_closure_command_batches() {
    let mut registry = Registry::new();

    registry.commands(|commands| {
        commands
            .define::<SelectAll, TestTarget>(|command| command.shortcut(Shortcut::ctrl('a')))
            .define::<Copy, TestTarget>(|command| command.shortcut(Shortcut::ctrl('c')));
    });

    assert_eq!(
        registry
            .shortcut_command(Shortcut::ctrl('a'))
            .map(|route| route.command()),
        Some(SELECT_ALL)
    );
    assert_eq!(
        registry
            .shortcut_command(Shortcut::ctrl('c'))
            .map(|route| route.command()),
        Some(COPY)
    );
}

#[test]
fn built_in_edit_commands_expose_expected_metadata() {
    let mut registry = Registry::new();
    let text_target = crate::text::command::text_target_kind();

    registry.commands(|commands| {
        crate::text::command::define::<SelectAll>(commands, |command| command);
        crate::text::command::define::<Paste>(commands, |command| command);
    });

    let default = registry.command::<SelectAll>().expect("select all command");
    let paste = registry.command::<Paste>().expect("paste command");
    let insert = Definition::for_command::<InsertText, TestTarget>();

    assert_eq!(default.target(), text_target);
    assert_eq!(paste.target(), text_target);
    assert_eq!(insert.target(), target::Kind::of_type::<TestTarget>());
    assert!(!default.accepts_repeat());
    assert!(insert.accepts_repeat());
    assert!(paste.accepts_repeat());
}

#[test]
fn command_macro_defines_typed_command_metadata() {
    let command = Definition::for_command::<MacroGenerated, TestTarget>();

    assert_eq!(MacroGenerated::NAME, "macro_generated");
    assert_eq!(MacroGenerated::DISPLAY, "Macro Generated");
    assert_eq!(command.hint(), Some("Generated by command macro"));
    assert_eq!(command.target(), target::Kind::of_type::<TestTarget>());
    assert!(command.accepts_repeat());
}

#[test]
fn raw_and_invocation_preserve_source_context_and_origin() {
    let window = window::Id::new(1);
    let path = ui::Path::from(TEXT_BOX);
    let context = Context::path(window, path.clone());
    let request = Raw::from_key(SELECT_ALL, Source::Shortcut, context.clone())
        .with_args(args::Raw::Bool(true))
        .with_origin(path.clone());
    let invocation = Invocation::from(request.clone());

    assert_eq!(request.command(), SELECT_ALL);
    assert_eq!(request.source(), Source::Shortcut);
    assert_eq!(request.context(), &context);
    assert_eq!(request.origin(), Some(&path));
    assert_eq!(invocation.command(), SELECT_ALL);
    assert_eq!(invocation.origin(), Some(&path));
    assert!(!invocation.repeated());
}

#[test]
fn typed_call_can_be_unresolved_scope_first() {
    let call = Call::<InsertText>::new::<TestTarget>("abc".to_owned())
        .expect("string args should validate");

    assert_eq!(call.args().as_str(), "abc");
    assert_eq!(call.window_id(), None);
    assert_eq!(call.scope(), &Scope::Current);
    assert_eq!(call.requested_context(), None);
}

#[test]
fn typed_call_erases_args_into_raw_call_after_context_resolution() {
    let window = window::Id::new(1);
    let path = ui::Path::from(TEXT_BOX);
    let context = Context::path(window, path.clone());
    let call = Call::<InsertText>::for_context::<TestTarget>("abc".to_owned(), context.clone())
        .expect("string args should validate")
        .with_source(Source::Shortcut)
        .with_origin(path.clone());

    assert_eq!(call.args().as_str(), "abc");
    assert_eq!(call.window_id(), Some(window));
    assert_eq!(call.scope(), context.scope());
    assert_eq!(call.requested_context(), Some(context.clone()));

    let request = Raw::from(call);

    assert_eq!(request.command(), INSERT_TEXT);
    assert_eq!(request.source(), Source::Shortcut);
    assert_eq!(request.context(), &context);
    assert_eq!(request.args(), &args::Raw::Text("abc".to_owned()));
    assert_eq!(request.origin(), Some(&path));
}

#[test]
fn typed_call_can_preserve_invocation_context() {
    let window = window::Id::new(1);
    let path = ui::Path::from(TEXT_BOX);
    let context = Context::path(window, path.clone());
    let invocation =
        Invocation::new::<SelectAll>(Source::Shortcut, context.clone()).with_origin(path.clone());

    let call = Call::<SelectAll>::for_invocation::<TestTarget, _>((), &invocation)
        .expect("unit args should validate");

    assert_eq!(call.source(), Source::Shortcut);
    assert_eq!(call.requested_context(), Some(context));
    assert_eq!(call.origin(), Some(&path));
}

#[test]
fn repeated_invocation_round_trips_through_call_and_raw() {
    let window = window::Id::new(1);
    let context = Context::window(window);
    let invocation =
        Invocation::new::<SelectAll>(Source::Shortcut, context.clone()).with_repeated(true);

    let call = Call::<SelectAll>::for_invocation::<TestTarget, _>((), &invocation)
        .expect("unit args should validate");
    let request = Raw::from(call);
    let invocation = Invocation::from(request.clone());

    assert_eq!(request.context(), &context);
    assert!(request.repeated());
    assert!(invocation.repeated());
}

#[test]
fn registry_prepares_any_call_for_target_dispatch() {
    let window = window::Id::new(1);
    let path = ui::Path::from(TEXT_BOX);
    let context = Context::path(window, path.clone());
    let request =
        Raw::from_key(SELECT_ALL, Source::Shortcut, context.clone()).with_origin(path.clone());
    let mut registry = Registry::new();

    registry.define::<SelectAll, TestTarget>(|command| command);
    registry.set_state_key(SELECT_ALL, context.clone(), State::available());

    let pending = registry
        .prepare_call(request)
        .expect("matching unit Raw should prepare erased call");

    assert!(pending.is::<SelectAll>());
    assert!(!pending.is::<Copy>());

    let call = pending
        .into_call::<SelectAll>()
        .expect("matching erased call should recover typed call");

    assert_eq!(call.source(), Source::Shortcut);
    assert_eq!(call.requested_context(), Some(context));
    assert_eq!(call.origin(), Some(&path));
}

#[test]
fn path_args_are_preserved_in_raw_calls() {
    let window = window::Id::new(1);
    let path = PathBuf::from("notes.txt");
    let call = Call::<SaveAs>::for_window::<TestTarget>(path.clone(), window)
        .expect("path args should validate");
    let request = Raw::from(call);

    assert_eq!(request.args(), &args::Raw::Path(path));
}

#[test]
fn registry_prepares_payload_args_for_any_calls() {
    let mut registry = Registry::new();
    let context = Context::window(window::Id::new(1));
    let request = Raw::from_key(CUSTOM_FLAG, Source::Programmatic, context.clone())
        .with_args(args::Raw::Bool(true));

    registry.define::<CustomFlag, FlagTarget>(|command| command);
    registry.set_state_key(CUSTOM_FLAG, context.clone(), State::available());

    let call = registry
        .prepare_call(request)
        .expect("valid bool payload should prepare")
        .into_call::<CustomFlag>()
        .expect("prepared call should retain command type");

    assert_eq!(call.args(), &true);
    assert_eq!(call.requested_context(), Some(context));
}

#[test]
fn registry_rejects_invalid_decoded_args_for_raw_calls() {
    let mut registry = Registry::new();
    let context = Context::window(window::Id::new(1));
    let request = Raw::from_key(Key::of::<SaveAs>(), Source::Programmatic, context.clone())
        .with_args(args::Raw::Path(PathBuf::new()));

    registry.define::<SaveAs, TestTarget>(|command| command);
    registry.set_state_key(Key::of::<SaveAs>(), context.clone(), State::available());

    assert_eq!(
        registry.prepare_call(request),
        Err(Rejection::InvalidArgs {
            command: SaveAs::NAME,
            error: args::Error::Invalid("path cannot be empty"),
        })
    );
}

#[test]
fn registry_rejects_wrong_payload_shape_through_args_decoder() {
    let mut registry = Registry::new();
    let context = Context::window(window::Id::new(1));
    let request = Raw::from_key(INSERT_TEXT, Source::Programmatic, context.clone())
        .with_args(args::Raw::Bool(true));

    registry.define::<InsertText, TestTarget>(|command| command);
    registry.set_state_key(INSERT_TEXT, context.clone(), State::available());

    assert_eq!(
        registry.prepare_call(request),
        Err(Rejection::InvalidArgs {
            command: InsertText::NAME,
            error: args::Error::InvalidRaw("expected text args"),
        })
    );
}

#[test]
fn typed_call_builds_requested_context_from_window_and_scope() {
    let window = window::Id::new(1);
    let path = ui::Path::from(TEXT_BOX);
    let call = Call::<InsertText>::for_window::<TestTarget>("abc".to_owned(), window)
        .expect("string args should validate")
        .with_scope(Scope::Path(path.clone()));

    assert_eq!(call.window_id(), Some(window));
    assert_eq!(call.scope(), &Scope::Path(path.clone()));
    assert_eq!(call.requested_context(), Some(Context::path(window, path)));
}

#[test]
fn typed_target_contract_invokes_with_command_args() {
    let context = Context::window(window::Id::new(1));
    let invocation = Invocation::new::<CustomFlag>(Source::Programmatic, context);
    let mut target = FlagTarget { value: false };

    assert_eq!(invocation.command(), CUSTOM_FLAG);

    let response = target.invoke(true, invocation);

    assert_eq!(response.into_output(), ());
    assert!(target.value);
}

#[test]
fn response_can_accumulate_followup_command_effects() {
    let window = window::Id::new(1);
    let context = Context::window(window);
    let call = Call::<CustomFlag>::for_context::<FlagTarget>(true, context.clone())
        .expect("bool args should validate");
    let response = Response::output("done".to_owned()).then_call(call);

    assert_eq!(response.effects().len(), 1);

    let (output, effects) = response.into_parts();

    assert_eq!(output, "done");
    let [Effect::Call(call)] = effects.as_slice() else {
        panic!("expected one follow-up call effect");
    };
    assert!(call.is::<CustomFlag>());
    assert_eq!(call.context(), Some(context));
}

#[test]
fn response_can_pipe_output_into_followup_command_args() {
    let response = Response::output(Some("copy".to_owned()))
        .pipe_with::<InsertText, TestTarget>(Source::Programmatic, Scope::Focused, |text| {
            text.unwrap_or_default()
        })
        .expect("pipe args should validate");
    let (_, effects) = response.into_parts();
    let [Effect::Call(call)] = effects.as_slice() else {
        panic!("expected one piped call effect");
    };

    assert!(call.is::<InsertText>());
    assert_eq!(call.context(), None);
}

#[test]
fn response_can_accumulate_task_effects() {
    let response = Response::none().then_task(effect::Task::new(|| Ok(Response::none())));

    assert_eq!(response.effects().len(), 1);
    assert!(matches!(response.effects()[0], Effect::Task(_)));
}

#[test]
fn registry_invokes_typed_target_after_validation() {
    let mut registry = Registry::new();
    let context = Context::window(window::Id::new(1));
    let call = Call::<CustomFlag>::for_context::<FlagTarget>(true, context.clone())
        .expect("bool args should validate");
    let mut target = FlagTarget { value: false };

    registry.define::<CustomFlag, FlagTarget>(|command| command);
    registry.project_target_states(&target, context.clone());

    let response = registry
        .invoke_on(&mut target, call)
        .expect("registered enabled command should invoke");

    assert_eq!(response.into_output(), ());
    assert!(target.value);
}

#[test]
fn registry_rejects_unresolved_typed_target_invocation() {
    let mut registry = Registry::new();
    let call = Call::<CustomFlag>::new::<FlagTarget>(true).expect("bool args should validate");
    let mut target = FlagTarget { value: false };

    registry.define::<CustomFlag, FlagTarget>(|command| command);

    assert_eq!(
        registry.invoke_on(&mut target, call),
        Err(Rejection::UnresolvedTarget {
            command: CustomFlag::NAME,
        })
    );
    assert!(!target.value);
}

#[test]
fn registry_rejects_disabled_typed_target_invocation() {
    let mut registry = Registry::new();
    let context = Context::window(window::Id::new(1));
    let call = Call::<CustomFlag>::for_context::<FlagTarget>(true, context.clone())
        .expect("bool args should validate");
    let mut target = FlagTarget { value: false };

    registry.define::<CustomFlag, FlagTarget>(|command| command);
    registry.set_state::<CustomFlag>(context.clone(), State::unavailable());

    assert_eq!(
        registry.invoke_on(&mut target, call),
        Err(Rejection::Disabled {
            command: CustomFlag::NAME,
            context,
        })
    );
    assert!(!target.value);
}

#[test]
fn effect_can_wrap_typed_command_call() {
    let window = window::Id::new(1);
    let context = Context::window(window);
    let call = Call::<CustomFlag>::for_context::<FlagTarget>(true, context.clone())
        .expect("bool args should validate")
        .with_source(Source::Programmatic);

    let effect = Effect::call(call);

    assert_eq!(effect.kind(), effect::Kind::Call);
    let Effect::Call(call) = effect else {
        panic!("expected call effect");
    };
    assert!(call.is::<CustomFlag>());
    assert_eq!(call.context(), Some(context));
}

#[test]
fn can_execute_uses_args_decoder_for_payload_validation() {
    let mut registry = Registry::new();
    let context = Context::window(window::Id::new(1));

    registry.register(Definition::for_command::<InsertText, TestTarget>());
    registry.set_state_key(INSERT_TEXT, context.clone(), State::available());

    let insert_request = Raw::from_key(INSERT_TEXT, Source::Programmatic, context.clone())
        .with_args(args::Raw::Text("abc".to_owned()));
    let bad_insert_request =
        Raw::from_key(INSERT_TEXT, Source::Programmatic, context).with_args(args::Raw::Bool(true));

    assert!(registry.can_execute(&insert_request));
    assert!(!registry.can_execute(&bad_insert_request));

    let call = registry
        .prepare_call(insert_request)
        .expect("valid text args should prepare")
        .into_call::<InsertText>()
        .expect("insert text should downcast");
    assert_eq!(call.args(), "abc");
}
